using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace Sample.Generators
{
    /// <summary>
    /// Emits a single source-generated file `Sample.Generated.GeneratedHello` into any
    /// project that references this analyser. The output is byte-stable across runs so
    /// the indexer's SHA gate has something to validate ("unchanged generated bytes
    /// don't reindex", per design.md).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class HelloGenerator : IIncrementalGenerator
    {
        private const string Source = @"namespace Sample.Generated
{
    public static class GeneratedHello
    {
        public static string Greet() => ""hi"";
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("GeneratedHello.g.cs", SourceText.From(Source, Encoding.UTF8));
            });
        }
    }

    /// <summary>
    /// Test-only generator used by Roslyn structural identity tests. Its hint is intentionally
    /// shared with <see cref="SecondStorageIdentityGenerator"/>; the output varies per consuming
    /// project and marker text so incremental generated-owner updates can be asserted.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class StorageIdentityGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.CompilationProvider,
                static (productionContext, compilation) =>
                {
                    var assemblyName = ToIdentifier(
                        compilation.AssemblyName ?? "Unknown");
                    var isVersionTwo = compilation.SyntaxTrees.Any(tree =>
                        tree.GetText().ToString().IndexOf(
                            "GEN_VERSION_2",
                            StringComparison.Ordinal) >= 0);
                    var version = isVersionTwo ? "V2" : "V1";
                    var source = $@"namespace Generated.{assemblyName};

public static class GeneratedState{version}
{{
    public const int Version = {(isVersionTwo ? 2 : 1)};
    public static int ReadSecond() => SecondGeneratedState.Value;
}}
";
                    productionContext.AddSource(
                        "SharedOwner.g.cs",
                        SourceText.From(source, Encoding.UTF8));
                });
        }

        private static string ToIdentifier(string value)
        {
            var chars = value
                .Select(character =>
                    char.IsLetterOrDigit(character) || character == '_'
                        ? character
                        : '_')
                .ToArray();
            return chars.Length == 0 || char.IsDigit(chars[0])
                ? "_" + new string(chars)
                : new string(chars);
        }
    }

    /// <summary>
    /// Second owner with the same hint name, proving generator identity cannot be reduced to a
    /// display path or hint.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class SecondStorageIdentityGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.CompilationProvider,
                static (productionContext, compilation) =>
                {
                    var assemblyName = new string(
                        (compilation.AssemblyName ?? "Unknown")
                        .Select(character =>
                            char.IsLetterOrDigit(character) || character == '_'
                                ? character
                                : '_')
                        .ToArray());
                    var source = $@"namespace Generated.{assemblyName};

public static class SecondGeneratedState
{{
    public const int Value = 7;
}}
";
                    productionContext.AddSource(
                        "SharedOwner.g.cs",
                        SourceText.From(source, Encoding.UTF8));
                });
        }
    }

    /// <summary>
    /// Emits a generated DllImport only while a consuming syntax tree contains the marker
    /// GENERATE_INTEROP_IMPORT. Incremental interop tests use the output's disappearance to
    /// verify stale generated owners trigger caller fanout and cleanup.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ConditionalInteropImportGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.CompilationProvider,
                static (productionContext, compilation) =>
                {
                    var enabled = compilation.SyntaxTrees.Any(tree =>
                        tree.GetText().ToString().IndexOf(
                            "GENERATE_INTEROP_IMPORT",
                            StringComparison.Ordinal) >= 0);
                    var keepOwner = compilation.SyntaxTrees.Any(tree =>
                        tree.GetText().ToString().IndexOf(
                            "KEEP_GENERATED_INTEROP_OWNER",
                            StringComparison.Ordinal) >= 0);
                    if (!enabled && !keepOwner)
                    {
                        return;
                    }

                    const string importSource = @"using System.Runtime.InteropServices;

namespace Generated.Interop;

internal static class NativeMethods
{
    [DllImport(""medalgo"", EntryPoint = ""generated_allocate"")]
    internal static extern System.IntPtr Allocate();
}
";
                    const string ordinarySource = @"namespace Generated.Interop;

internal static class NativeMethods
{
    internal static System.IntPtr Allocate() => System.IntPtr.Zero;
}
";
                    productionContext.AddSource(
                        "ConditionalInteropImport.g.cs",
                        SourceText.From(
                            enabled ? importSource : ordinarySource,
                            Encoding.UTF8));
                });
        }
    }
}
