using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Sample.Generators
{
    /// <summary>
    /// Emits a single source-generated file `Sample.Generated.GeneratedHello` into any
    /// project that references this analyser. The output is byte-stable across runs so
    /// the indexer's SHA gate has something to validate ("unchanged generated bytes
    /// don't reindex", per design.md).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class HelloGenerator : IIncrementalGenerator
    {
        private const string Source = @"namespace Sample.Generated
{
    public static class GeneratedHello
    {
        public static string Greet() => ""hi"";
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("GeneratedHello.g.cs", SourceText.From(Source, Encoding.UTF8));
            });
        }
    }
}
